name: tests

on: 
    pull_request
jobs:
    build:
        runs-on: ubuntu-latest
        steps: 
          - uses: actions/checkout@V2
          - run: cd Ticketing && cd auth && npm install && npm run test:ci
